apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::869935092837:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-Jr8rISMtR4bY
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::869935092837:user/noor
      username: noor
    - groups:
     
kind: ConfigMap

metadata:
  creationTimestamp: "2025-04-22T10:19:53Z"
  name: aws-auth
  namespace: kube-system
  uid: a4ff12b6-44a0-4d5a-9705-03d61f7d9acc
